In [ ]:
# Series of problems where students need to find the mistake and fix the code

##word##

In [ ]:
?heloo

# Data types problems

In [2]:
# Problem: Access the second element of the array
A = [1,2,3,4]
A(1)

2

In [ ]:
# Answer
# Replace parentheses for square brackets
A[1]

In [1]:
# Select the Python command that returns the last 3 temperature values of:
A = [28.7, 25.0, 41.5, 29.9, 42.9, 44.8]
A[-3:]

[29.9, 42.9, 44.8]

In [10]:
# If a and b are the legs of a right triangle, which line of code will return the hypotenuse?
import math
a=3
b=4
print((a**2 + b**2)**0.5)
# print(sqrt(a**2 + b**2))
# print([a**2 + b**2]**0.5)

5.0


In [16]:
# URL: https://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b6907d289e10d714a6e88b30761fae22
# Source: https://openweathermap.org/current

W = {"coord":{"lon":-0.13,"lat":51.51},
     "weather":[{"id":300,"main":"Drizzle","description":"light intensity drizzle","icon":"09d"}],
     "base":"stations",
     "main":{"temp":280.32,"pressure":1012,"humidity":81,"temp_min":279.15,"temp_max":281.15},
     "visibility":10000,
     "wind":{"speed":4.1,"deg":80},
     "clouds":{"all":90},
     "dt":1485789600,
     "sys":{"type":1,"id":5091,"message":0.0103,"country":"GB","sunrise":1485762037,"sunset":1485794875},
     "id":2643743,
     "name":"London",
     "cod":200}

print(W['coord'])
print(W['main']['temp'])
print(W['wind']["speed"])

{'lon': -0.13, 'lat': 51.51}
280.32
4.1


In [19]:
mytuple = (10,20,30)
print(mytuple[1])
mytuple[0] = 11;

20


TypeError: 'tuple' object does not support item assignment

# Strings problems

In [16]:
# Problem: Fix the code so that we can build a the full path for the file:
# Result: /User/Documents/Datafiles/myfile.csv, must be a string

filename = "myfile"
extension = .csv
path = "/User/Documents/Datafiles/"
fullpath = [path + filename + extension]
print(fullpath)


SyntaxError: invalid syntax (<ipython-input-16-b52774eee195>, line 5)

In [3]:
# Answer
# Add quotation marks to extension (must be a string)
# Remove square brackets from fullpath so that the results is a string and not a list

filename = "myfile"
extension = ".csv"
path = "/User/Documents/Datafiles/"
fullpath = path + filename + extension

print(fullpath)
print(type(fullpath))

/User/Documents/Datafiles/myfile.csv
<class 'str'>


In [12]:
B = [ [1,2,3], [4,5,6, ['a','b','c']]]
B[1][3][0]
B[1][0][3]

TypeError: 'int' object is not subscriptable

# Datetime problem

In [16]:
# Assignment: Write a script that calculates the day of the year for the current date and time.
# The script must output both the DOY as an integer and the fraction of the day.

import datetime
import math

# Calculate the day of the year (DOY) for any given date.
date = datetime.datetime.now()
dateOne = datetime.datetime(date.year,1,1)
dateDiff = date - dateOne; # Operations between datetime objects result in datetime objects
doy_float = dateDiff.total_seconds()/86400 # gives the doy with decimal places
doy_int = math.floor(doy_float) # found that total_seconds is a method from the error of dateDiff.total_seconds
doy_fraction = doy_float - doy_int;

print(doy_float)
print('Day of the year: ' + str(doy_int))
print('Fraction of the day: ' + str(round(doy_fraction,2)))



42.62220429774305
Day of the year: 43
Fraction of the day: -0.38


In [28]:
import datetime
start_date = datetime.datetime(1998,6,1)
end_date = datetime.datetime(2019,1,1)
diff_date = end_date - start_date
print("The result is:",diff_date.total_seconds()/3600)

The result is: 180456.0


# Random module problems

In [69]:
# Which of these Python commands returns a random integer from the range 10 to 120?
# A random float within a specific range
import random
min_val = 20
max_val = 120
ans1 = (max_val - min_val)*random.random() + min_val


ans2 = random.randrange(10,120,0.1)

ans3 = random.randrange(0,1)

print(ans1)
print(ans2)
print(ans3)

ValueError: non-integer step for randrange()

# For loops problems

In [24]:
# Problem: Fix the for loop so that it prints each element of the list one time

soils = ["mollisols", "hapludols", "alfisols"]
for x in soils:
    print(soil)

['mollisols', 'hapludols', 'alfisols']
['mollisols', 'hapludols', 'alfisols']
['mollisols', 'hapludols', 'alfisols']


In [ ]:
# Answer
# Replace soil for x
soils = ["mollisols", "hapludols", "alfisols"]
for x in soils:
    print(x)

# If statement problems

In [17]:
# Problem: Fix the if statement so that it print "It's an Apple" when A = 'apple'
A = "apple"

if A = "apple"
    print("Not an apple")  
else
   print("It's an apple")


SyntaxError: invalid syntax (<ipython-input-17-fb280fd773ef>, line 4)

In [7]:
# Answer
# Add equal sign
# Add colons after if and else
# Correct logic (swap statements)

A == "apple"

if A == "apple":
    print("It's an apple")
else:
    print("Not an apple")

It's an apple


# Numpy Problems

In [71]:
# Problem: Write five python commands to extract:
# top row
# bottom row
# right-most column
# left-most column
# upper-right 3x3 matrix

import numpy as np
np.random.seed(0)
M = np.random.randint(0,10,[5,5])
print(M)


[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]
 [6 7 7 8 1]
 [5 9 8 9 4]]


In [77]:
# Answer
# Top row
print(M[0,:]) # or simply M[0]

# Bottom row
print(M[-1,:])

#Right-most column
print(M[:,-1])

# Left-most column
print(M[:,0])

# upper-right 3x3 matrix
print(M[0:3,2:]) # common mistake is to do M[0:2, 2:-1]

# Read 2: as all columns (or rows) from index 2 to the end (all the remaining, to the end)

[5 0 3 3 7]
[5 9 8 9 4]
[7 4 1 1 4]
[5 9 7 6 5]
[[3 3 7]
 [5 2 4]
 [8 8 1]]
